name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          TOKEN_HF_PULSE_AI: ${{ secrets.TOKEN_HF_PULSE_AI }}
        run: git push https://ML-Owl:$TOKEN_HF_PULSE_AI@huggingface.co/spaces/ML-Owl/FAANG-Pulse-AI main --force