name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push to Hugging Face
        uses: huggingface/hub-sync@v0.1.4
        with:
          github_repo_id: dr-cagri-tanriover/FAANG-Pulse-AI
          huggingface_repo_id: ML-Owl/FAANG-Pulse-AI
          repo_type: space
          hf_token: ${{ secrets.HF_TOKEN }}